### ISSUE TITLE
Grid position must be both odd or even

### ISSUE THREAD

**Issue by draxxris** [emlun/factorio-blueprint-aligner#1]
Can't seem to get a valid blueprint out of this. It always says it must have grid position of odd or even, yet even when I set them to that, or don't have it set at all, I still get this error message.

```
0eNqV181uozAQB/B38Rki/B04Vto+wEo9VdWKJFZqiRgEpmpU8e5roK1KO1VmThEJ/smZ+WPsN3ZoRtf1PkRWvbEh1F0e2/zc+9N8/cqq0mTsOn9MGasPQ9uM0eXzfZ0PZ1bFfnQZ88c2DKx6TII/h7qZx8Zr51jFfHQXlrFQX+arvvYNS5IPJ5dwPj1lzIXoo3fr+OXi+i+Ml4Pr0w2fI49j/+JO+QJkrGuHNKYN75M06yRVkk++d8f1JzFlP0CBA61YwGILGgCUOJCvoLkNqk9wiMk6P8ffSLuQ+vaf1miyxJIGSwqOJS2alFhyjyY1liyxpEa3hxdoE90fzrGmQTeIC6y5TrPckhYi5WZpyN+XD6A/u7VDZqdvP0JcbdXjc+3Dr7YRJFsjl6SF5GIrckhEP0vrNLmdIMUSlRJU9jRFcFApiYqEFFEQFQ0qHJcws/tQvqdAQaogzg3smZBEBeyZUDRFgj0TmqjAPSNmWcI9I2ZZwtUlZlnC1SVmWYHVlcQsK7C6khMVsLqSmF0FVlcSs6vA6kpidjVcXWJ2NVxdYnY1XF1idjVcXWJ2NVxdYnYNWF1V4N54ajW+bXE1JBLX5PkNfXtNVsi9fbGY9sebOR1FlsNK9eVMlLGmPrh0nmF3D/f3f/6mL15cP6xbpD1XthRWKmWVUNP0H305YWg=
```

**Comment by emlun** [comment]
Thanks! Should be fixed in version 1.0.3.

Turns out I was computing the blueprint width and height slightly incorrectly, and apparently also looking at the wrong bounding box for curved rails specifically. This meant the height/width calculation, and therefore also the center snapping point, was thrown way off when there were curved rails at the edges of the blueprint. So your example was a big help!
